version: '{build}'
branches:
  only:
  - master
  - appveyor-artifact
image: Visual Studio 2017
configuration: Release
platform: x64
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: 7z a WickedEngineEditor.zip @artifacts_editor.txt
artifacts:
- path: WickedEngineEditor.zip
  name: Editor
