version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x64
build:
  parallel: true
  verbosity: minimal
  
after_build:
  
artifacts:
  - path: x64/Release/Editor.exe
  - name: Executable
  
  - path: WickedEngine/shaders/*.cso
  - name: Compiled Shaders
  
  - path: WickedEngine/fonts/*
  - name: Fonts
  
